{
 "title": "Patras gauges [max/avg/events] per year",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "query": "SELECT DISTINCT YEAR(Date2) as year from pm25"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of PM2.5 measurements (year)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(`pm2.5_atm`)\r\nfrom pm25\r\nwhere YEAR(Date2) = $year ;"
    }
   ]
  },
  {
   "title": "Average values (year)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(`pm2.5_atm`+0) as avg_pm25\r\nFROM `pm25`\r\nwhere YEAR(Date2) = $year "
    }
   ]
  },
  {
   "title": "Number of  articles/events (year)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT( DISTINCT Title)\r\nfrom pm25\r\n where YEAR(Date2) = $year ;"
    }
   ]
  },
  {
   "title": "Maximum values (year)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(`pm2.5_atm`+0) as max_pm_25\r\nFROM `pm25`\r\nwhere YEAR(Date2) = $year "
    }
   ]
  }
 ]
}