{
 "title": "Patras visualisations [max/avg/events] all years (2018-2023)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of PM2.5 measurements (all years)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(`pm2.5_atm`)\r\nfrom pm25"
    }
   ]
  },
  {
   "title": "Average PM2.5 (all years)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(`pm2.5_atm`+0) as avg_pm25\r\n\r\nfrom pm25"
    }
   ]
  },
  {
   "title": "Average PM2.5 (all years/per year)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT YEAR(Date2) as year, AVG(`pm2.5_atm`+0) as avg_pm\r\nfrom pm25\r\nGROUP BY YEAR(Date2)"
    }
   ]
  },
  {
   "title": "Number of  articles/events (all years)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT( DISTINCT Title)\r\nfrom pm25\r\n"
    }
   ]
  },
  {
   "title": "Maximum PM2.5 (all years)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(`pm2.5_atm`+0) as max_pm_25\r\n\r\nFROM `pm25`\r\n"
    }
   ]
  },
  {
   "title": "Maximum PM2.5 (all years/per year)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT YEAR(Date2) as year, MAX(`pm2.5_atm`+0) as max_pm\r\nfrom pm25\r\nGROUP BY YEAR(Date2)"
    }
   ]
  }
 ]
}